#!/usr/bin/env python3
"""Summarize decay sweep runs under an out_root.

Expects each decay run to have a regime_deltas.csv generated by
scripts/analysis/regime_delta_summary.py.

Usage:
  python scripts/analysis/decay_sweep_summary.py \
    --out_root out/suites/decay-sweep \
    --out_csv out/suites/decay-sweep/decay_sweep_summary.csv \
    --plot out/suites/decay-sweep/decay_sweep_summary.png
"""

import argparse
import csv
import os
import re
from pathlib import Path

import matplotlib

if "MPLCONFIGDIR" not in os.environ:
    os.environ["MPLCONFIGDIR"] = "/tmp/matplotlib"
matplotlib.use("Agg")
import matplotlib.pyplot as plt


DECAY_RE = re.compile(r"decay[-_]?([0-9.]+)")


def parse_decay(name):
    m = DECAY_RE.search(name)
    if not m:
        return None
    try:
        return float(m.group(1))
    except Exception:
        return None


def load_regime_deltas(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def mean_abs(rows, key):
    vals = []
    for row in rows:
        v = row.get(key)
        if v in (None, ""):
            continue
        try:
            vals.append(abs(float(v)))
        except Exception:
            continue
    return sum(vals) / len(vals) if vals else None


def mean_delta(rows, key):
    vals = []
    for row in rows:
        v = row.get(key)
        if v in (None, ""):
            continue
        try:
            vals.append(float(v))
        except Exception:
            continue
    return sum(vals) / len(vals) if vals else None


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_root", required=True)
    ap.add_argument("--out_csv", default="")
    ap.add_argument("--plot", default="")
    args = ap.parse_args(argv)

    out_root = Path(args.out_root)
    runs = []
    for child in out_root.iterdir():
        if not child.is_dir():
            continue
        decay = parse_decay(child.name)
        if decay is None:
            continue
        csv_path = child / "regime_deltas.csv"
        if not csv_path.exists():
            continue
        rows = load_regime_deltas(csv_path)
        runs.append((decay, child.name, rows))

    if not runs:
        raise SystemExit("no decay runs found with regime_deltas.csv")

    runs.sort(key=lambda x: x[0])
    out_csv = args.out_csv or str(out_root / "decay_sweep_summary.csv")
    Path(os.path.dirname(out_csv) or ".").mkdir(parents=True, exist_ok=True)

    summary_rows = []
    for decay, name, rows in runs:
        summary_rows.append({
            "run": name,
            "decay": decay,
            "retention": 1.0 - decay,
            "mean_abs_self_drift_delta": mean_abs(rows, "self_drift_delta"),
            "mean_abs_state_effect_delta": mean_abs(rows, "state_effect_delta"),
            "mean_loss_delta": mean_delta(rows, "loss_delta"),
            "mean_entropy_delta": mean_delta(rows, "stats_entropy_delta"),
            "mean_top1_delta": mean_delta(rows, "stats_top1_conf_delta"),
        })

    with open(out_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "run",
                "decay",
                "retention",
                "mean_abs_self_drift_delta",
                "mean_abs_state_effect_delta",
                "mean_loss_delta",
                "mean_entropy_delta",
                "mean_top1_delta",
            ],
        )
        writer.writeheader()
        for row in summary_rows:
            writer.writerow(row)

    if args.plot:
        decays = [r["decay"] for r in summary_rows]
        drift = [r["mean_abs_self_drift_delta"] for r in summary_rows]
        effect = [r["mean_abs_state_effect_delta"] for r in summary_rows]
        fig, ax = plt.subplots(figsize=(6, 4))
        ax.plot(decays, drift, marker="o", label="mean |Δself_drift|")
        ax.plot(decays, effect, marker="o", label="mean |Δstate_effect|")
        ax.set_xlabel("self_state_decay (update rate)")
        ax.set_ylabel("mean absolute delta")
        ax.grid(True, alpha=0.2)
        ax.legend(fontsize=8)
        fig.tight_layout()
        Path(os.path.dirname(args.plot) or ".").mkdir(parents=True, exist_ok=True)
        fig.savefig(args.plot, dpi=150)
        plt.close(fig)

    print(f"wrote {out_csv}")
    if args.plot:
        print(f"wrote {args.plot}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
